### PR TITLE
Fixing initialization of self.info

### PR DESCRIPTION
**Pull request by sisaha9**
Fixes https://github.com/autorope/donkeycar/issues/1086

### CODE REVIEW

**Comment by DocGarbanzo** [comment]
@Maximellerbach - can you have a look at this?

**Comment by Maximellerbach** [comment]
@DocGarbanzo the type of self.info['lidar'] should be a np.array, I'm not sure of the expected behavior when the array is empty ? Are we checking somewhere if the array of point is empty / matches the expected shape the model needs ?

**Comment by DocGarbanzo** [comment]
> @DocGarbanzo the type of self.info['lidar'] should be a np.array, I'm not sure of the expected behavior when the array is empty ? Are we checking somewhere if the array of point is empty / matches the expected shape the model needs ?

Currently the lidar data is not used in any models. For now it's just being recorded into the tub, as it would be returned in the `run_threaded` method. Here, we would need a native python list, but not an `np.array`.

**Comment by Maximellerbach** [comment]
> 

Maybe I'm missing something, why should it be a python list ? I am currently returning from GymDonkeycar a numpy array, if you confirm it should be a list then I will also change it on this side

**Comment by Ezward** [comment]
I think the older drivers return an np.array() and the newer drivers return a python list.  I would go with the newer drivers.  This is what the new driver puts out: https://github.com/autorope/donkeycar/blob/c4d90910e0e1b5056dc8961a09c7e5eb1ba18ffe/donkeycar/parts/lidar.py#L171

**Comment by Maximellerbach** [comment]
Ok ! I will then align with those.
What does the time and scan values look like ?

**Review by Maximellerbach — APPROVED** [review]

**Review by DocGarbanzo — APPROVED** [review]
Thanks @sisaha9

**Pull request merged**
