### PR TITLE
Add 'xboxswapped' joystick device

### PR DESCRIPTION
**Pull request by nvtkaszpir**
This effectively just swaps original XboxOne controller mini-joysticks - orofinally the fleft is for seering sideways and riht for acceleration.

This change allows to define new joystick mapping (which is just swapped the above one), so that throttle is on left joystick, and side steering is on right stick.

This conforms with joystick steering via web interface (when using game controller with web browser such as Chrome, and also follows steering scheme in other games such as Dirt 2 if controller is directly connected to the car, for example via bluetooth).

Other buttons are left intact (especially triggers which follow Forza style).

### CODE REVIEW

**Comment by tikurahul** [comment]
Can you consider making this a part of the joystick configuration and make it a part of the original class ?

Alternatively, your new `JoystickController` can extend the current `XboxOneJoyStickController` with the overriden maps.

**Comment by nvtkaszpir** [comment]
You mean to to move 'swap' option to the base class?

**Comment by tikurahul** [comment]
Yes. Make the swapping an option in `cfg_complete.py` and use that to make the swap.

**Comment by nvtkaszpir** [comment]
Well, looking at the code it's not that easy as it sounds.
Each class inherits from JoystickController but each device uses different axes names   - compare Xbox and WiiU - method init_trigger_maps has different axis_trigger_map per device:
Xbox has 'left_stick_horz' while WiiU there is 'LEFT_STICK_X'.


So there are two options:
1. for each device controller add additional 'if' statement for swapped device remap (and then define for example JOYSTICK_SWAP_STICKS=True), but then it would be applicable only for specific devices (so JOYSTICK_SWAP_STICKS would be useless for certain devices)
2. creating new class for specific device with modified mapping (just as in this PR)

**Comment by tikurahul** [comment]
1 sounds messy.
For option 2, you have another choice. Have the swapped controller extend the current `XBoxOneJoyStickController` and override the one method you need to. That way you don't have to duplicate everything.

**Comment by nvtkaszpir** [comment]
Yeah, thanks for the inf, but it still would require to define new controller type.

**Comment by tawnkramer** [comment]
it's just a dict of names and function pointers, so you can also write a generic `swap steering and throttle` that works for all controllers. Just iterate over the dict and find the key that sets the steering, throttle, and then remap.

**Comment by tawnkramer** [comment]
I will roll the new class into dev branch. leave the swapping up to you if you want to do it.

**Comment by nvtkaszpir** [comment]
ok

**Pull request closed without merging**
