### PR TITLE
@peterpantechland changes for mapping to be correct.

### PR DESCRIPTION
**Pull request by wallarug**
As discussed with Peter.  There were strange values generated by the mapping function.  

Moving around the MID and top values should improve / fix this.

### CODE REVIEW

**Comment by sctse999** [comment]
I need to look into the changes. Will get back to you.

**Comment by wallarug** [comment]
kk ;)

**Comment by sctse999** [comment]
I tested this but it looks like it is not compatible with web controller. It is flipping the web controller's input.

**Comment by sctse999** [comment]
@tawnkramer we can just close this PR without merging. Thanks.

**Pull request closed without merging**
