### PR TITLE
add support for four motors differential drive

### PR DESCRIPTION
**Pull request by jjakubassa**
Adds support for four motors as requested by myself at Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#41. Strongly based on suggestions by @Ezward. I tested it succesfully on my Freenove 4WD Car. 

(my first open source contribution 🎉)

### CODE REVIEW

**Review by Ezward — COMMENTED** [review]
I opened a tracking issue and added a question for you here https://github.com/autorope/donkeycar/issues/1084#issuecomment-1376164738

**Review by Ezward — COMMENTED** [review]
This looks good.  I'd like to know if you have been able to collect data and train a working autopilot with it.

**Comment by Ezward** [comment]
@jjakubassa have you tested this with the deep learning template; can you create a reliable autopilot with this drivetrain?

**Comment by jjakubassa** [comment]
@Ezward please see my comment [here](https://github.com/autorope/donkeycar/issues/1084#issuecomment-1437349889).

**Comment by Ezward** [comment]
We got feedback in the linked Issue that the solution worked to drive the wheels, but the chassis did not perform well with donkeycar and so was abandoned.  So I am closing the PR.

**Pull request closed without merging**
