### PR TITLE
Updated Docs for the Simulator (Part 1 - master)

### PR DESCRIPTION
**Pull request by wallarug**
Updated some of the documentation around the simulator after running through the instructions.  Found one inconsistency and added a helpful hit for people about what to put into the PATH.

### CODE REVIEW

**Comment by wallarug** [comment]
Thanks @tawnkramer any reason this didn't get merged properly?

**Comment by tawnkramer** [comment]
There was a merge conflict. After merging was just waiting for travis ci to
give the all clear. A bit silly given this is just a doc change.

**Comment by blown302** [comment]
Not silly at all ... :)

**Comment by tawnkramer** [comment]
Anyone know why this is stuck in “waiting for status to be reported “?

**Comment by wallarug** [comment]
Nope.  Should I redo the PR and push into dev instead?

**Pull request merged**
