### PR TITLE
Mm1 Enhancement

### PR DESCRIPTION
**Pull request by sctse999**
This is an enhancement to the existing MM1 donkey part. I have decoupled MM1 dependency from RC controller. Now MM1 can act as a joystick controller and a drive train independently. It means that we can use the MM1 with/without a RC controller, depending on the scnenario.

Other changes:
1. Add config for MM1 max throttle and steering adjustment
2. Add test case to robohat.py
3. Add map_range_float to util
4. Fix missing import in robohat.py
5. Bug fix: wrong order of parameter passed into robohat.py in manage.py
6. Tidy up: Consistently use the order angle then throttle in robohat.py
7. Add "MM1" option to controller type and drive train in cfg_complete.py
8. Add code.py and dependency under donkeycar/contrib/robohat

### CODE REVIEW

**Comment by wallarug** [comment]
@sctse999  is there any changes to the code.py file?

**Comment by sctse999** [comment]
@wallarug except fixing the datastr issue, no big changes. For details, see PR to your repo

https://github.com/robotics-masters/mm1-hat-cpy-native/pull/8

**Comment by sctse999** [comment]
@tawnkramer  @tikurahul do you have time to take a look at this PR? Feel free to let me know the changes you need to approve this. thanks a lot.

p.s.: If you need the MM1 for testing the code, @wallarug should be happy to provide it to you.

**Comment by tawnkramer** [comment]
Sorry for delay. Can you resolve conflicts and happy to merge.

**Comment by tawnkramer** [comment]
Thanks!

**Pull request merged**
