### PR TITLE
crop and normalize outside of model

### PR DESCRIPTION
**Pull request by tawnkramer**
this creates a part to pre-process image before inference to apply crop, as well as normalize images. It also crops and normalizes during training.

### CODE REVIEW

**Comment by tawnkramer** [comment]
I trained a few models with and without crop in the simulator. looked good to me so far. would you like to take a look before merge?

**Comment by tikurahul** [comment]
Will take a look.

**Comment by tikurahul** [comment]
All Keras parts will have to move to derived properties for width and height for the models to work correctly. 
https://github.com/autorope/donkeycar/blob/dev/donkeycar/parts/tensorrt.py#L40 for e.g will be incorrect if cropping is involved.

**Comment by tawnkramer** [comment]
yes, it's unfortunate, but I don't see a better way. Don't think we want to overload the current vars image_w, image_h with the crop folded in. So I made new derived TARGET_W, TARGET_H. I've fixed all references, including the one you point out there. Does this strike you as the right approach or did you see a better way forward?

**Pull request merged**
