### PR TITLE
Ref ticket #394 - Readding tubclean web interface files.

### PR DESCRIPTION
**Pull request by Schmill**
+ tubclean interface re-added.
+ Hash values for scripts updated appropriately (Chrome doesn't block them now)
+ Added a "Fast forward 10 seconds" function to the interface.

### CODE REVIEW

**Comment by tawnkramer** [comment]
Nice. Thanks! Any chance you could add a random access click to set read head?

**Comment by tawnkramer** [comment]
I get the web interface. But it's not displaying any files for me.

**Comment by tawnkramer** [comment]
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:8886/static/bootstrap/3.3.7/js/bootstrap.min.js' with computed SHA-256 integrity 'U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8='. The resource has been blocked.

3 times and then|
Uncaught ReferenceError: $ is not defined
    at tub.js:1

**Comment by Schmill** [comment]
Hmm, which browser are you using?
I had that problem and had to recalculate the hashes.
I'll take a look at what's involved in the hashes, but it would be useful to know which browser you are using too; I was using Chrome

**Comment by tawnkramer** [comment]
chrome 75 on windows 10. I regenerated sha384 hashes and those working for me.

**Comment by tawnkramer** [comment]
I pushed those changes to dev. are you able to try those?

**Comment by Schmill** [comment]
Will do.
I don't know much about the hashes but I wonder if they include the date / time stamp on the script files in which case it would be different each time.
Might be worth a "touch" on those script files and see if the hashes STILL work for you?
Will try dev on my home machine when I get in.

**Comment by Schmill** [comment]
Incidentally, what did you mean by a "random access click" ?

"Any chance you could add a random access click to set read head"

**Comment by Schmill** [comment]
@tawnkramer - No, those hashes don't work for me, I now get the hash messages again, which is what I got originally...

I think there is something strange happening with the hashes, perhaps because the hashed files are part of the commit - I really don't know.

When you get (got) the error in Chrome in theory you should have got it for each of the js files, but lets consider the one you quoted:

> Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:8886/static/bootstrap/3.3.7/js/bootstrap.min.js' with computed SHA-256 integrity 'U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8='. The resource has been blocked.

On my PC, for the same file, I get:

> Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:8886/static/bootstrap/3.3.7/js/bootstrap.min.js' with computed SHA-256 integrity 'NkYOSU5MYoRDr97UCydDte3ppKdvtPe57yNFzH5Z/WQ='. The resource has been blocked.

Straight away this shows that for some reason the integrity hash is being calculated _differently_ in the two instances.

We could spend time working out _why_ but as these files are in the repo I'd favour removing the integrity tag completely for ease (we aren't bothered about _actually_ checking the integrity, since the files are local and may have legitimately been changed)

` donkeycar/management/tub_web/base.html | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/donkeycar/management/tub_web/base.html b/donkeycar/management/tub_web/base.html
index a05b876..fb1c1c2 100644
--- a/donkeycar/management/tub_web/base.html
+++ b/donkeycar/management/tub_web/base.html
@@ -6,19 +6,19 @@
 
   <script
     src="/static/jquery-3.1.1.min.js"
-    integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
     crossorigin="anonymous"></script>
 
   <script
     src="/static/ui/1.12.1/jquery-ui.min.js"
-    integrity="sha384-Dziy8F2VlJQLMShA6FHWNul/veM9bCkRUaLqr199K94ntO5QUrLJBEbYegdSkkqX"
     crossorigin="anonymous"></script>
 
   <script type="text/javascript" src="/static/nipple.js"></script>
 
 
   <link href="/static/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
-  <script src="/static/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
+  <script 
+    src="/static/bootstrap/3.3.7/js/bootstrap.min.js" 
+    crossorigin="anonymous"></script>
 
 
   <link href="/static/style.css" rel="stylesheet">
`

**Comment by tawnkramer** [comment]
I’m fine with removing the check.

**Comment by tawnkramer** [comment]
Something that would allow you to click on the image track to set the
current time, rather than playing or fast forwarding.

**Comment by tawnkramer** [comment]
I've removed the integrity check. Works fine. That's pushed now to dev.

**Comment by Schmill** [comment]
I'll remove the check and get back to you on the image track ;)

**Comment by Schmill** [comment]
@tawnkramer 
> Something that would allow you to click on the image track to set the
current time, rather than playing or fast forwarding.

See pull request #398

**Pull request merged**
