### PR TITLE
L298N motor control

### PR DESCRIPTION
**Pull request by raskaman**
adding logic to control the motors with a L298N

### CODE REVIEW

**Comment by raskaman** [comment]
related issue:
https://github.com/autorope/donkeycar/issues/724

**Comment by DocGarbanzo** [comment]
Hi @raskaman - thanks for your PR. This looks good to me. Can you please do the following?
* Create the PR against the `dev` branch
* Squash your 3 commits into one
We can then merge it.

**Review by DocGarbanzo — CHANGES_REQUESTED** [review]
Hi @raskaman - thanks for your PR. This looks good to me. Can you please do the following?

* Create the PR against the dev branch
* Squash your 3 commits into one
 
We can then merge it.

**Comment by raskaman** [comment]
> Hi @raskaman - thanks for your PR. This looks good to me. Can you please do the following?
> 
> * Create the PR against the dev branch
> * Squash your 3 commits into one
> 
> We can then merge it.

Hi @DocGarbanzo , I have made a new PR with the requested changes:
https://github.com/autorope/donkeycar/pull/829

**Pull request closed without merging**
