### PR TITLE
Add SerialController part.

### PR DESCRIPTION
**Pull request by Schoonology**
This part allows the control of the Donkey Car via the RX/TX pins on the Raspberry Pi.

This part was requested from a couple members of the Slack, originally created for my [Autonomous Robot Challenge](https://www.hackster.io/contests/arm2018) entry.

### CODE REVIEW

**Comment by wroscoe** [comment]
This looks awesome. I'm moving non core parts out of this repo so I've made a reverence to this pull here... https://github.com/autorope/donkeyparts/issues/3

**Comment by Schoonology** [comment]
Fantastic! Thanks for the note, too; I'll move any parts I build in the future to that repo.

**Comment by Schoonology** [comment]
Actually, now I see that's just an Issue on the other repo. Would you like me to resubmit this as a PR to `autorope/donkeyparts`?

**Comment by wroscoe** [comment]
Even better would be if you were to make a separate repo for the part like this (https://github.com/autorope/donkeypart_bluetooth_game_controller) that could be installed via pip. I could then fork it into autorope to help people find it. Thanks!

**Pull request closed without merging**
