### PR TITLE
Added Validation of user input for PWM calibration

### PR DESCRIPTION
**Pull request by Labonneguigue**
Validation that the user inputs an integer and that the integer is indeed in range.

#322

### CODE REVIEW

**Comment by Labonneguigue** [comment]
I see your point but I disagree with the idea. I don't think we want this 
`a = 'lkdfhisoe78347834 (())&/&745  '`
 to be a valid input.
Regex are beautiful but I think we should use them when needed. When the input is mistakenly not directly castable to int, we should reject the input.

**Comment by scitronboy** [comment]
I agree with you @Labonneguigue , I think regexs are overkill and are unnecessary for this. Also, a user might have intended to input something different than the regex interprets it as.

**Comment by scitronboy** [comment]
For example, if a user wants to input `1239`, but the user accidentally inputs `123i` because `i` is just below `9` on a keyboard, then the regex would remove the `i` and act like the user inputed `123`, which would _not_ be what the user wanted.

**Comment by rampageservices** [comment]
No , 123 WOULD be what the user wanted.
It would strip the back space characters which is the original problem that
I was having if you reference the original issue.

**Comment by scitronboy** [comment]
No, not necessarily. The user would _not_ want `123` if the user had meant to input `1234`.

**Pull request merged**
