### PR TITLE
Be explicit about newline characters

### PR DESCRIPTION
**Pull request by tikurahul**

### CODE REVIEW

**Comment by DocGarbanzo** [comment]
I think there is os.linesep instead of \n or \n\r if we want to be system agnostic to new lines.

**Comment by tikurahul** [comment]
`os.linesep` would mean that it could be problematic to collect data on Linux and train on Windows. This way irrespective of the platform we are explicit about the newline character and we get portability.

**Comment by DocGarbanzo** [comment]
Ok you just hard-replaced the file endings now with windows format. Usually if you transfer text files to windows you would just run `unix2dos` on them. Now under linux/mac I believe the text files will look odd in a standard text editor (emacs, nano, less, etc) because they will have `^R` in them, or not?

**Comment by tikurahul** [comment]
No. I use the same for both. It will look correct on editors everywhere because editors already support different types of line endings.

**Pull request merged**
