### PR TITLE
Added Installation Video

### PR DESCRIPTION
**Pull request by jaskarannagi19**
A complete video from Installation to training on a simulator.

### CODE REVIEW

**Comment by tikurahul** [comment]
I don't think having this link here is useful. It's useful to know how to use the simulator, so thank you for making the video. Please blog about it instead. That might be a better avenue for it.

**Comment by jaskarannagi19** [comment]
@tikurahul  I opened a new request for its edition into the docs of installation setup of linux. That should be its place

**Comment by tawnkramer** [comment]
We have a doc page for the simulator. Don’t you think it’s better there?

**Comment by jaskarannagi19** [comment]
Ok I'll close this request and put up there.

**Pull request closed without merging**
