### PR TITLE
Support for sixad ps3controller on Nano

### PR DESCRIPTION
**Pull request by fengye**
It's hard to pair PS3 controller to Jetson Nano however we still can use sixad, which continuously maintained by Retropie team, to pair and connect the controller. Details of instructions [here ](https://retropie.org.uk/docs/PS3-Controller/#for-older-versions-of-retropie) and [there(out of date)](http://booting-rpi.blogspot.com/2012/08/dualshock-3-and-raspberry-pi.html), though referred to Pi but works on Nano too.

After successfully connecting the PS3 controller to Nano, there's a need to support the sixad version of PS3 button/axis mapping. Users can swap the PS3Joystick object with PS3JoystickSixAd in PS3JoystickController.init_js(). Tested with OEM PS3 controller on Nano 4GB kit.

Side note: we might want to update the docs about PS3 controller compatibility on Nano too.

### CODE REVIEW

**Comment by DocGarbanzo** [comment]
@fengye - looks good to me, but please rebase on dev and squash your 4 commits into one and force-push to your branch.

**Comment by fengye** [comment]
Yeah I can do that but does donkeycar has a guideline for how to contribute, things like rebasing and squashing? I can't see on the docs page or homepage.

**Comment by fengye** [comment]
Looks I've erroneously committed stuff into my local `dev` branch so I'll open another pull request for the same changes. See PR #931

**Comment by DocGarbanzo** [comment]
> Yeah I can do that but does donkeycar has a guideline for how to contribute, things like rebasing and squashing? I can't see on the docs page or homepage.

This is a valid question. There is a video by @sctse999 - which is somewhere linked in the Discord forum. We are working on adding more videos and links on the Donkey Car page, so it is expected to appear there soon.

**Pull request closed without merging**
