### PR TITLE
Fix tubhist figure storage location

### PR DESCRIPTION
**Pull request by jasonleung101**
Fixed the tubhist figure storage location from the root directory to target tub directory.

### CODE REVIEW

**Comment by tawnkramer** [comment]
I don't like putting it in the tub dir. That's not where non-tub data goes. I understand that perhaps you don't want it to default to the current dir. Perhaps we can add an option to specify output path on command line?

**Comment by jasonleung101** [comment]
Thanks for the suggestion. I added a new parameter called "out" for a user to specify the output path on the command line. If a user did not enter the specify the output path, the output will be set by default just like before. Otherwise, the histogram will store in the specified output path. Thank you.

**Comment by jasonleung101** [comment]
Sorry for the missing argument.

**Comment by tawnkramer** [comment]
looks good, thanks!

**Pull request merged**
