### PR TITLE
USYD Brakes

### PR DESCRIPTION
**Pull request by wallarug**
**New functionality for Simulator**

- Brake Communication between sim and donkey vehicle

### CODE REVIEW

**Comment by wallarug** [comment]
This commit contains the following changes.

- Added a `brake` variable to a number of functions in a number of files.
  - donkeycar/parts/dgym.py `run_threaded`
  - donkeycar/parts/launch.py `run`
  - donkeycar/parts/web_controller/web.py `run return value`

- Reflect these function changes in the following templates:
  - complete.py
  - basic.py

All other changes to tubs and datastore should not be of any notable change - they are coming from changes made by rahul that were merged in during the brake changes.

**Comment by wallarug** [comment]
Also has fix for #652 by changing the track in the comment to something that works.

**Comment by tikurahul** [comment]
@wallarug you are reordering commits here. 

Please isolate your changes and apply them on top of commits and not interleave them with the existing git history. Please use `git pull --rebase` instead of a regular `pull` because pull is a shorthand for a fetch and merge. Ideally we should strive for never having to merge and only have fast forwards.

**Comment by tikurahul** [comment]
Also please squash your changes into a single commit by using `git rebase -i`. That makes your changes easier to isolate if we need to.

**Pull request closed without merging**
