### PR TITLE
cropping works

### PR DESCRIPTION
**Pull request by HansKristjan99**

### CODE REVIEW

**Comment by Ezward** [comment]
@HansKristjan99 we need more before we can review this;
There is no description at all for this pull request.  We need some context before we can review this.  Remember that we also have to test this, so if you have tested this please tell us how and on what hardware and with what relevant configuration.
1. What: What is this pull request doing.  Something like , "Implements cropping for training and inference on the linear model" or 'Fixes bug described in Issue #32"
2. Why: explain the value of this feature or fix.
3. How: What changes did you make to implement the What.
4. Test: How should we test this and what other features might this affect?

**Comment by Ezward** [comment]
@HansKristjan99 I've not looked deeply at this, but we do have a  cropping feature that can be applied to any model.  See TRANFORMATIONS and ROI_CROP_TOP in donkeycar/templates/cfg_complete.py.

**Review by DocGarbanzo — CHANGES_REQUESTED** [review]
This code is not in a state where it can be reviewed.

**Comment by Ezward** [comment]
I have not heard anything from the author so I am going to close this PR without merging.

**Pull request closed without merging**
