### PR TITLE
Add axis names and button names to Joystick.

### PR DESCRIPTION
**Pull request by tikurahul**
* This step helps discover mappings not already pre-existing and
provides a way to dicover and modify defaults.

* Adds Forza mode for the XboxOne controller.

### CODE REVIEW

**Comment by tawnkramer** [comment]
Hi Rahul. Thanks for the extra details in the documentation. And added defaults in Joystick class. But I don't want to add the extra command to tie the shoulder button to the throttle by default. The PS3 and PS4 controllers are prone to accidental pressing of the shoulder analog buttons when you set them down on a table. Can you remove that, please?

**Comment by tikurahul** [comment]
The `right_trigger` addition is only applicable to the `XboxJoystickController` which also happens to be in the same file. PS3, PS4 defaults remain the same. For the XboxOne controller, it's actually a nicer way to control the car. 

https://github.com/autorope/donkeycar/blob/9e2bbd777e1464b34a81258934388d160d549260/donkeycar/parts/controller.py#L1049

**Comment by adammconway** [comment]
We had lots of thrashing on this feature, lots of PRs etc.  The solution might be to make it automatic.  We just look at whatever value is bigger, the stick or the trigger and use that.  That way it can be either/or

**Comment by tikurahul** [comment]
The triggers work the way they should. Rather than the `right_trigger` do the work for both acceleration and deceleration we assign `right_trigger` to acceleration and `left_trigger` to deceleration. We do this by mapping raw axis values from `-1.` to `1.` to their `magnitude`.  This magnitude then gets scaled appropriately by `set_throttle`. 

We reverse the `magnitude` for the `left_trigger`. 
Tests: Tested on my Jetson Nano.

**Comment by tawnkramer** [comment]
Can you resolve w base so I can merge?

**Comment by tikurahul** [comment]
I rebased by changes with the `master` branch.

**Pull request merged**
