### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by jaskarannagi19**
Added Installation Video Link in linux doc and merging request in default dev branch.

### CODE REVIEW

**Comment by tikurahul** [comment]
Your changes don’t add any new meaningful information. We already mention that `tensorflow-gpu` does require Nvidia GPUs. 

Also your training video does not add any new meaningful information. You can always blog about it on your own.

**Comment by dlarue** [comment]
Yes but I had to spend 30+ minutes supporting someone who didn't understand that there was a requirement for NVidia hardware in order to run the tf-gpu version.  Maybe he didn't understand what "NVidia GPU" meant so I added the "NVidia Graphics Card notice on the optional comment.

The person also had said it said "optional" and didn't feel it meant optional based on anything else.  You know, like how it says OpenCV is optional..

**Comment by jaskarannagi19** [comment]
First of all please don't pick up a fight. I'll blog about it no problem. Idea came to my mind when a group of kids wanted a build a self driving car they found this donkey car repo. But they are beginner they didn't know how to run commands. I know you must be laughing at them but they are 8-10 years old. I was so thrilled by it to find that there are young people who wants to see this stuff happening so I made this video and send them over. I can now imagine how people who are very new to computer and learning can make use of it. Rest it's up to you I'll definitely blog about it on medium.

**Comment by dlarue** [comment]
@jaskarannagi19   I think the point is that this is a complex project with hardware to hack, hardware to wire and wire correct or you will burn things up, then 2 different software platforms.  Not something to hand to 8-10 year old kids. But definitely something to show to kids and even let them drive to collect data.  FWIW, I make a bootable ISO with scripts which make the whole process on the software side easier. And those scripts could be behind a GUi with simple buttons to do 5 steps to making an autonomous vehicle.  Then there is the simulator too.

For now, the docs are for those who can understand the hardware, software and deal with the understanding required to make it work.  We have adults having problems following the documents  as it is.  For videos, most of the time they are posted to youtube and links added to the support forum.  We should have a pinned page for instructional videos.

**Comment by tikurahul** [comment]
Sorry, I did not mean to belittle your contributions. I was only trying to point out that this particular contribution does not belong in reference docs. 

We might want to consider highlighting all community produced videos and instructional material. That would be very useful, however this imho is not a please for that.

**Comment by jaskarannagi19** [comment]
> Sorry, I did not mean to belittle your contributions. I was only trying to point out that this particular contribution does not belong in reference docs.
> 
> We might want to consider highlighting all community produced videos and instructional material. That would be very useful, however this imho is not a place for that.

Well actually I posted this in donkey slack channel and Twan advised me to open a pull request because recently we did find 2-3 people asking for process. That motivated me to open the pull request. It's up to you guys but I'll blog about it that is under process :)

**Pull request closed without merging**
